import Provider from "./provider";

import styles from "./layout.module.scss";

import "@/styles/global.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className={styles.wrapper}>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
