export { default as BuildingIcon } from "./building.svg";
export { default as GithubIcon } from "./github.svg";
export { default as GmailIcon } from "./gmail.svg";
export { default as LinkIcon } from "./link.svg";
export { default as MenuIcon } from "./menu.svg";
export { default as PhoneIcon } from "./phone.svg";
export { default as SchoolIcon } from "./school.svg";
export { default as DateIcon } from "./date.svg";
export { default as UserIcon } from "./user.svg";
